### ISSUE TITLE
Error while pip install picharsso

### ISSUE THREAD

**Issue by xicopetry** [aarondecosta/image-to-ascii#3]
$ **pip install picharsso**
Collecting picharsso
  Using cached https://files.pythonhosted.org/packages/59/f5/5dbd2fc59eab3eafced5658ecaa9f79667d71cd129056a06aa3e45d376d1/picharsso-1.21-py3-none-any.whl
Collecting opencv-python (from picharsso)
  Using cached https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8g68awtu/opencv-python/setup.py", line 9, in <module>
        import skbuild
    **ModuleNotFoundError: No module named 'skbuild'**
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8g68awtu/opencv-python/

**Comment by kelvindecosta** [comment]
As per my understanding, this command is trying to install version `1.21` of picharsso as it has been cached locally.
Although it used to work well, it is not as useful as versions `^2.`.

I suggest you try the following command to install the latest version:

```bash
pip install picharsso -U
```

**Comment by xicopetry** [comment]
Tks for the reply @kelvindecosta !

Well, I did this, and still got the error:

$ pip install picharsso -U
Collecting picharsso
  Using cached https://files.pythonhosted.org/packages/59/f5/5dbd2fc59eab3eafced5658ecaa9f79667d71cd129056a06aa3e45d376d1/picharsso-1.21-py3-none-any.whl
Collecting sty (from picharsso)
  Downloading https://files.pythonhosted.org/packages/42/63/5039335264e33c49bfafe4ad133cca6b3209423fdd9a041cf9c4cf1b4fb8/sty-1.0.0b12-py3-none-any.whl
Collecting opencv-python (from picharsso)
  Using cached https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6vkwgndh/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6vkwgndh/opencv-python/

**Comment by kelvindecosta** [comment]
That's strange.
The command is still trying to install `1.21`.

My reasoning is that pip tries to upgrade picharsso to the latest version that is compatible with your Python environment.
Are you working with Python 3.8?

**Comment by xicopetry** [comment]
no
$ python --version
Python 3.7.5

**Comment by kelvindecosta** [comment]
Ah, that makes sense.

Unfortunately, the latest "compatible" version for Python `3.7`, via pip, is indeed `1.21`.

I don't remember exactly why I specified `>=3.8` in the `setup.py`.
Maybe it is still possible to install `2.0.1` within a Python `3.7` environment.
You could try cloning the repository and then installing it.

```bash
git clone https://github.com/kelvindecosta/picharsso && cd picharsso
pip install .
```
I am not certain that this would work.

Upgrading to Python `3.8` is probably your best bet.

**Comment by xicopetry** [comment]
Sure, tks again for the replies!

I updated to 3.8 and worked perfectly!
